name: .NET Core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'    # Don't build if README or other .md changes
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest-ppc64le
    strategy:
      matrix:
        dotnet: [ '7.0.115', '8.0.101' ]
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: |
        echo '{"sdk":{"version": "${{ matrix.dotnet }}"}}' > ./global.json
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create Package
      run: dotnet pack --configuration Release
      
