name: .NET Core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'    # Don't build if README or other .md changes
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest-ppc64le
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.115'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create Package
      run: dotnet pack --configuration Release
      
